import type { Metadata } from "next";
import { Figtree, Inter } from "next/font/google";
import { Sidebar } from "@/src/components/ui/Sidebar";
import "./globals.css";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children 
}: { 
  children: React.ReactNode 
}) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row">
        <Sidebar />
        <main className="flex-1 typeset typeset-docs overflow-auto">{children}</main>
      </body>
    </html>
  );
}
