"""add farms and donation offers

Revision ID: 5e46b5d4b7b3
Revises: f7035c4d0ba7
Create Date: 2026-09-06 20:38:36.985114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e46b5d4b7b3"
down_revision: str | Sequence[str] | None = "f7035c4d0ba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_farms_valid_latitude")),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name=op.f("ck_farms_valid_longitude")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farms")),
        sa.UniqueConstraint("name", name=op.f("uq_farms_name")),
    )
    op.create_index(op.f("ix_farms_region"), "farms", ["region"], unique=False)
    op.create_table(
        "donation_offers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("farm_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pickup_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'allocated', 'completed', 'cancelled')",
            name=op.f("ck_donation_offers_valid_status"),
        ),
        sa.CheckConstraint(
            "pickup_by IS NULL OR available_from IS NULL OR pickup_by >= available_from",
            name=op.f("ck_donation_offers_valid_pickup_window"),
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"], ["farms.id"], name=op.f("fk_donation_offers_farm_id_farms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_donation_offers")),
    )
    op.create_index(
        op.f("ix_donation_offers_farm_id"), "donation_offers", ["farm_id"], unique=False
    )
    op.create_index(
        op.f("ix_donation_offers_pickup_by"), "donation_offers", ["pickup_by"], unique=False
    )
    op.create_index(op.f("ix_donation_offers_status"), "donation_offers", ["status"], unique=False)
    op.create_table(
        "donation_offer_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("donation_offer_id", sa.UUID(), nullable=False),
        sa.Column("food_category_code", sa.String(length=50), nullable=False),
        sa.Column("pounds", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pounds > 0", name=op.f("ck_donation_offer_items_positive_pounds")),
        sa.ForeignKeyConstraint(
            ["donation_offer_id"],
            ["donation_offers.id"],
            name=op.f("fk_donation_offer_items_donation_offer_id_donation_offers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["food_category_code"],
            ["food_categories.code"],
            name=op.f("fk_donation_offer_items_food_category_code_food_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_donation_offer_items")),
        sa.UniqueConstraint("donation_offer_id", "food_category_code", name="offer_food_category"),
    )
    op.create_index(
        op.f("ix_donation_offer_items_donation_offer_id"),
        "donation_offer_items",
        ["donation_offer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_donation_offer_items_donation_offer_id"), table_name="donation_offer_items"
    )
    op.drop_table("donation_offer_items")
    op.drop_index(op.f("ix_donation_offers_status"), table_name="donation_offers")
    op.drop_index(op.f("ix_donation_offers_pickup_by"), table_name="donation_offers")
    op.drop_index(op.f("ix_donation_offers_farm_id"), table_name="donation_offers")
    op.drop_table("donation_offers")
    op.drop_index(op.f("ix_farms_region"), table_name="farms")
    op.drop_table("farms")
    # ### end Alembic commands ###
