"""create recipient aliases table

Revision ID: 9a3e9c223cb0
Revises: b8dca8797e4b
Create Date: 2026-09-05 15:31:38.083861

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a3e9c223cb0"
down_revision: str | Sequence[str] | None = "b8dca8797e4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipient_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("source_name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("recipient_site_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('include', 'merge', 'exclude')",
            name=op.f("ck_recipient_aliases_valid_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_site_id"],
            ["recipient_sites.id"],
            name=op.f("fk_recipient_aliases_recipient_site_id_recipient_sites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipient_aliases")),
        sa.UniqueConstraint("source_system", "normalized_name", name="source_name_per_system"),
    )
    op.create_index(
        op.f("ix_recipient_aliases_recipient_site_id"),
        "recipient_aliases",
        ["recipient_site_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipient_aliases_recipient_site_id"), table_name="recipient_aliases")
    op.drop_table("recipient_aliases")
    # ### end Alembic commands ###
