"""add recommendation snapshots

Revision ID: a600f02c78d2
Revises: ca2e5a8dcdca
Create Date: 2026-09-07 14:28:03.503897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a600f02c78d2"
down_revision: str | Sequence[str] | None = "ca2e5a8dcdca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("donation_offer_id", sa.UUID(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column(
            "policy_version",
            sa.String(length=50),
            server_default="v1",
            nullable=False,
        ),
        sa.Column("tie_window_days", sa.Integer(), nullable=False),
        sa.Column(
            "offered_total_pounds",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column(
            "offered_items_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "offered_total_pounds > 0",
            name=op.f("ck_recommendation_runs_positive_offered_total_pounds"),
        ),
        sa.CheckConstraint(
            "tie_window_days >= 0",
            name=op.f("ck_recommendation_runs_nonnegative_tie_window_days"),
        ),
        sa.ForeignKeyConstraint(
            ["donation_offer_id"],
            ["donation_offers.id"],
            name=op.f("fk_recommendation_runs_donation_offer_id_donation_offers"),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_recommendation_runs"),
        ),
    )
    op.create_index(
        op.f("ix_recommendation_runs_donation_offer_id"),
        "recommendation_runs",
        ["donation_offer_id"],
        unique=False,
    )

    op.create_table(
        "recommendation_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recommendation_run_id", sa.UUID(), nullable=False),
        sa.Column("recipient_site_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("recipient_name", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("last_delivery_date", sa.Date(), nullable=True),
        sa.Column("days_since_last_delivery", sa.Integer(), nullable=True),
        sa.Column("is_overdue", sa.Boolean(), nullable=False),
        sa.Column("deliveries_last_30_days", sa.Integer(), nullable=False),
        sa.Column(
            "pounds_last_30_days",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("total_deliveries", sa.Integer(), nullable=False),
        sa.Column(
            "total_pounds",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("matched_category_count", sa.Integer(), nullable=False),
        sa.Column(
            "known_potential_pounds",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("has_unknown_capacity", sa.Boolean(), nullable=False),
        sa.Column(
            "food_matches_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            ("days_since_last_delivery IS NULL OR days_since_last_delivery >= 0"),
            name=op.f("ck_recommendation_candidates_nonnegative_delivery_days"),
        ),
        sa.CheckConstraint(
            "deliveries_last_30_days >= 0",
            name=op.f("ck_recommendation_candidates_nonnegative_recent_deliveries"),
        ),
        sa.CheckConstraint(
            "known_potential_pounds >= 0",
            name=op.f("ck_recommendation_candidates_nonnegative_known_potential_pounds"),
        ),
        sa.CheckConstraint(
            "matched_category_count > 0",
            name=op.f("ck_recommendation_candidates_positive_matched_category_count"),
        ),
        sa.CheckConstraint(
            "pounds_last_30_days >= 0",
            name=op.f("ck_recommendation_candidates_nonnegative_recent_pounds"),
        ),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5",
            name=op.f("ck_recommendation_candidates_priority_range"),
        ),
        sa.CheckConstraint(
            "rank > 0",
            name=op.f("ck_recommendation_candidates_positive_rank"),
        ),
        sa.CheckConstraint(
            "total_deliveries >= 0",
            name=op.f("ck_recommendation_candidates_nonnegative_total_deliveries"),
        ),
        sa.CheckConstraint(
            "total_pounds >= 0",
            name=op.f("ck_recommendation_candidates_nonnegative_total_pounds"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_site_id"],
            ["recipient_sites.id"],
            name=op.f("fk_recommendation_candidates_recipient_site_id_recipient_sites"),
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_run_id"],
            ["recommendation_runs.id"],
            name=op.f("fk_recommendation_candidates_recommendation_run_id_recommendation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_recommendation_candidates"),
        ),
        sa.UniqueConstraint(
            "recommendation_run_id",
            "rank",
            name="recommendation_run_rank",
        ),
        sa.UniqueConstraint(
            "recommendation_run_id",
            "recipient_site_id",
            name="recommendation_run_recipient",
        ),
    )
    op.create_index(
        op.f("ix_recommendation_candidates_recipient_site_id"),
        "recommendation_candidates",
        ["recipient_site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_candidates_recommendation_run_id"),
        "recommendation_candidates",
        ["recommendation_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_candidates_recommendation_run_id"),
        table_name="recommendation_candidates",
    )
    op.drop_index(
        op.f("ix_recommendation_candidates_recipient_site_id"),
        table_name="recommendation_candidates",
    )
    op.drop_table("recommendation_candidates")
    op.drop_index(
        op.f("ix_recommendation_runs_donation_offer_id"),
        table_name="recommendation_runs",
    )
    op.drop_table("recommendation_runs")
    # ### end Alembic commands ###
