"""add recipient aliases

Revision ID: b8dca8797e4b
Revises: e8b24b3a7ed5
Create Date: 2026-09-05 15:25:29.291936

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b8dca8797e4b"
down_revision: str | Sequence[str] | None = "e8b24b3a7ed5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
