"""add recipient food preferences

Revision ID: ca2e5a8dcdca
Revises: 5e46b5d4b7b3
Create Date: 2026-09-06 20:56:54.605850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca2e5a8dcdca"
down_revision: str | Sequence[str] | None = "5e46b5d4b7b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipient_food_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient_site_id", sa.UUID(), nullable=False),
        sa.Column("food_category_code", sa.String(length=50), nullable=False),
        sa.Column("maximum_pounds", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "maximum_pounds IS NULL OR maximum_pounds > 0",
            name=op.f("ck_recipient_food_preferences_positive_maximum_pounds"),
        ),
        sa.ForeignKeyConstraint(
            ["food_category_code"],
            ["food_categories.code"],
            name=op.f("fk_recipient_food_preferences_food_category_code_food_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_site_id"],
            ["recipient_sites.id"],
            name=op.f("fk_recipient_food_preferences_recipient_site_id_recipient_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipient_food_preferences")),
        sa.UniqueConstraint(
            "recipient_site_id", "food_category_code", name="recipient_food_category"
        ),
    )
    op.create_index(
        op.f("ix_recipient_food_preferences_food_category_code"),
        "recipient_food_preferences",
        ["food_category_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_food_preferences_recipient_site_id"),
        "recipient_food_preferences",
        ["recipient_site_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recipient_food_preferences_recipient_site_id"),
        table_name="recipient_food_preferences",
    )
    op.drop_index(
        op.f("ix_recipient_food_preferences_food_category_code"),
        table_name="recipient_food_preferences",
    )
    op.drop_table("recipient_food_preferences")
    # ### end Alembic commands ###
