"""add historical import staging

Revision ID: e8b24b3a7ed5
Revises: e08c2c2e57f2
Create Date: 2026-09-01 20:14:40.250154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8b24b3a7ed5"
down_revision: str | Sequence[str] | None = "e08c2c2e57f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_sheet", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="staged", nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("review_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('staged', 'completed', 'failed')",
            name=op.f("ck_import_batches_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("file_sha256", name=op.f("uq_import_batches_file_sha256")),
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("sheet_name", sa.String(length=100), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.String(length=100), nullable=True),
        sa.Column("row_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column(
            "validation_issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            status IN (\n                'pending',\n                'needs_review',\n                'approved',\n                'rejected',\n                'imported'\n            )\n            ",
            name=op.f("ck_import_rows_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_rows_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint("batch_id", "sheet_name", "row_number", name="batch_sheet_row"),
    )
    op.create_index(op.f("ix_import_rows_batch_id"), "import_rows", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_import_rows_source_record_id"), "import_rows", ["source_record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_import_rows_source_record_id"), table_name="import_rows")
    op.drop_index(op.f("ix_import_rows_batch_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
