"""add historical deliveries

Revision ID: f7035c4d0ba7
Revises: 9a3e9c223cb0
Create Date: 2026-09-06 14:48:46.775004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7035c4d0ba7"
down_revision: str | Sequence[str] | None = "9a3e9c223cb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_categories",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_food_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_food_categories_name")),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient_site_id", sa.UUID(), nullable=False),
        sa.Column("import_row_id", sa.UUID(), nullable=True),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("source_record_id", sa.String(length=100), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("source_recipient_name", sa.String(length=300), nullable=True),
        sa.Column("recipient_location", sa.String(length=300), nullable=True),
        sa.Column("driver_name", sa.String(length=200), nullable=True),
        sa.Column("vehicle_name", sa.String(length=200), nullable=True),
        sa.Column("total_pounds", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_pounds >= 0", name=op.f("ck_deliveries_nonnegative_total_pounds")
        ),
        sa.ForeignKeyConstraint(
            ["import_row_id"],
            ["import_rows.id"],
            name=op.f("fk_deliveries_import_row_id_import_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_site_id"],
            ["recipient_sites.id"],
            name=op.f("fk_deliveries_recipient_site_id_recipient_sites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("import_row_id", name=op.f("uq_deliveries_import_row_id")),
        sa.UniqueConstraint("source_system", "source_record_id", name="source_record"),
    )
    op.create_index(
        op.f("ix_deliveries_delivery_date"), "deliveries", ["delivery_date"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_recipient_site_id"), "deliveries", ["recipient_site_id"], unique=False
    )
    op.create_table(
        "delivery_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("food_category_code", sa.String(length=50), nullable=False),
        sa.Column("pounds", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pounds > 0", name=op.f("ck_delivery_items_positive_pounds")),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_items_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["food_category_code"],
            ["food_categories.code"],
            name=op.f("fk_delivery_items_food_category_code_food_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_items")),
        sa.UniqueConstraint("delivery_id", "food_category_code", name="delivery_food_category"),
    )
    op.create_index(
        op.f("ix_delivery_items_delivery_id"), "delivery_items", ["delivery_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_items_delivery_id"), table_name="delivery_items")
    op.drop_table("delivery_items")
    op.drop_index(op.f("ix_deliveries_recipient_site_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_delivery_date"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_table("food_categories")
    # ### end Alembic commands ###
